- name: Install DevOps Tools
  hosts: all
  become_user: root
  become: true

  tasks:
    # Prerequisitos necesarios para instalar las herramientas devops
    - name: Update ppa repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - ppa:deadsnakes/ppa # Python
        - ppa:openjdk-r/ppa # Java

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    - name: Upgrade the packages
      apt:
        upgrade: dist

    - name: Install required system packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - openjdk-11-jdk
        - python3.8
        - python3-pip
        - python3-setuptools
        - gnupg
        - gnupg2

    - name: Install python libraries $ awscli
      pip:
        name: "{{ item }}"
        state: latest
        executable: pip3.8
        extra_args: --upgrade
      loop:
        - docker
        - boto
        - boto3
        - awscli

      # Ansible
    - name: Install ansible
      apt:
        name: ansible
        state: latest
        update_cache: yes

    # Docker
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes

    - name: Install docker
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Add users to docker group
      user:
        name: "{{ item }}"
        group: "docker"
        append: yes
      loop:
        - "ubuntu"
        - "jenkins"

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
        dest: /usr/bin/docker-compose
        mode: "u+x,g+x"

    # Jenkins
    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins.list
        update_cache: yes

    - name: Install jenkins
      apt:
        name: jenkins
        state: latest
        update_cache: yes

    # Kubernetes
    - name: Add kubernetes repository key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add kubernetes repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list
        update_cache: yes

    - name: Install kubernetes binaries
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - kubectl

    # Start services
    - name: Start and review the services are running
      systemd:
        name: "{{ item }}"
        daemon_reload: yes
        enabled: yes
        state: started
      loop:
        - docker
        - jenkins

    # Clean the system
    - name: Clean/remove useless packages
      apt:
        autoclean: yes
        autoremove: yes
